input_folder: /Volumes/RangerLab/Maternal Project Data/Ultrasound Files
output_folder: /Volumes/RangerLab/Maternal Project Data/Cropped Ultrasound Files
reference_image1: /Volumes/RangerLab/Maternal Project Data/Cropped Ultrasound Files/NP008/NP008_Abd/capture_4_2026-01-13T17-25-17.jpeg
reference_image2: /Volumes/RangerLab/Maternal Project Data/Cropped Ultrasound Files/P034/T2/P034_Abd_T2/capture_6_2026-04-30T10-58-48.jpeg

# Test file paths
# input_folder: /Volumes/RangerLab/Maternal Project Data/Test Files/Files
# output_folder: /Volumes/RangerLab/Maternal Project Data/Test Files/Cropped Files

# MSK folders, add more based on Ultrasound Study Data Spreadsheet
msk_folders:
  - NP015_Abd
  - P001_Abd_T1
  - P005_Abd_T1
  - P006_Abd_T1
  - P054_Abd_T2
  - P055_Abd_T2
  - P059_Abd_T2
  - P060_Abd_T2
  - P062_Abd_T2
  - P039_Abd_T3
  - P040_Abd_T3
